export const resData = [
  {
    id: "279863",
    name: "EatFit",
    cloudinaryImageId: "1d578bb732e03c6f591790eb7d2d88e2",
    locality: "Naharpur",
    areaName: "Rohini",
    costForTwo: "₹250 for two",
    cuisines: ["North Indian", "Home Food", "Healthy Food", "Indian"],
    avgRating: 4.2,
    parentId: "422576",
    avgRatingString: "4.2",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 23,
      lastMileTravel: 1.6,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "1.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2024-04-30 01:00:00",
      opened: true,
    },
    badges: {
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "options available",
          fontColor: "#7E808C",
        },
      ],
    },
    isOpen: true,
    type: "F",
    badgesV2: {},
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹100",
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
  },
  {
    id: "558789",
    name: "HRX by EatFit",
    cloudinaryImageId: "d8d85afa5c5e92461d30ff2ca867a587",
    locality: "7Th Sector",
    areaName: "Rohini",
    costForTwo: "₹450 for two",
    cuisines: ["Healthy Food", "Salads", "Keto", "Pastas"],
    avgRating: 4.6,
    parentId: "335529",
    avgRatingString: "4.6",
    totalRatingsString: "100+",
    sla: {
      deliveryTime: 23,
      lastMileTravel: 1.6,
      serviceability: "SERVICEABLE",
      slaString: "20-25 mins",
      lastMileTravelString: "1.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2024-04-30 01:00:00",
      opened: true,
    },
    badges: {
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "brand",
          fontColor: "#7E808C",
        },
      ],
    },
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {},
        textBased: {},
        textExtendedBadges: {
          badgeObject: [
            {
              attributes: {
                description: "",
                fontColor: "#7E808C",
                iconId: "guiltfree/GF_Logo_android_3x",
                shortDescription: "brand",
              },
            },
          ],
        },
      },
    },
    aggregatedDiscountInfoV3: {
      header: "50% OFF",
      subHeader: "UPTO ₹90",
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
  },
  {
    id: "555307",
    name: "Chaayos Chai+Snacks=Relax",
    cloudinaryImageId:
      "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/f92c604d-68cb-49db-8dec-9473650c363d_555307.JPG",
    locality: "Sector-7",
    areaName: "Rohini",
    costForTwo: "₹250 for two",
    cuisines: ["Bakery", "Beverages", "Chaat", "Desserts", "Home Food"],
    avgRating: 4.6,
    parentId: "281782",
    avgRatingString: "4.6",
    totalRatingsString: "1K+",
    sla: {
      deliveryTime: 28,
      lastMileTravel: 3.6,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "3.6 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2024-04-30 02:00:00",
      opened: true,
    },
    badges: {
      imageBadges: [
        {
          imageId: "Rxawards/_CATEGORY-Cafe%20&%20Chai.png",
          description: "Delivery!",
        },
      ],
      textExtendedBadges: [
        {
          iconId: "guiltfree/GF_Logo_android_3x",
          shortDescription: "options available",
          fontColor: "#7E808C",
        },
      ],
    },
    isOpen: true,
    type: "F",
    badgesV2: {
      entityBadges: {
        imageBased: {
          badgeObject: [
            {
              attributes: {
                description: "Delivery!",
                imageId: "Rxawards/_CATEGORY-Cafe%20&%20Chai.png",
              },
            },
          ],
        },
        textBased: {},
        textExtendedBadges: {
          badgeObject: [
            {
              attributes: {
                description: "",
                fontColor: "#7E808C",
                iconId: "guiltfree/GF_Logo_android_3x",
                shortDescription: "options available",
              },
            },
          ],
        },
      },
    },
    aggregatedDiscountInfoV3: {
      header: "60% OFF",
      subHeader: "UPTO ₹120",
    },
    differentiatedUi: {
      displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
      differentiatedUiMediaDetails: {
        mediaType: "ADS_MEDIA_ENUM_IMAGE",
        lottie: {},
        video: {},
      },
    },
    reviewsSummary: {},
    displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    restaurantOfferPresentationInfo: {},
  },
  {
    id: "603438",
    name: "Chinese Wok",
    cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
    locality: "Sector 7",
    areaName: "Rohini",
    costForTwo: "₹250 for two",
    cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
    avgRating: 4.1,
    parentId: "61955",
    avgRatingString: "4.1",
    totalRatingsString: "500+",
    sla: {
      deliveryTime: 27,
      lastMileTravel: 2.8,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.8 km",
      iconType: "ICON_TYPE_EMPTY",
    },
    availability: {
      nextCloseTime: "2024-04-29 23:00:00",
      opened: true,
    },
    badges: {},
    isOpen: true,
    type: "F",
  },

  {
    id: "89571",
    name: "UBQ by Barbeque Nation",
    cloudinaryImageId: "hjokc46njfhv2vzhbzoa",
    locality: "Rohini",
    areaName: "Rohini",
    costForTwo: "₹300 for two",
    cuisines: [
      "North Indian",
      "Barbecue",
      "Biryani",
      "Kebabs",
      "Mughlai",
      "Desserts",
    ],
    avgRating: 3.9,
    parentId: "10804",
    avgRatingString: "3.9",
    totalRatingsString: "5K+",
    sla: {
      deliveryTime: 33,
      lastMileTravel: 2.1,
      serviceability: "SERVICEABLE",
      slaString: "30-35 mins",
      lastMileTravelString: "2.1 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },

  {
    id: "55473",
    name: "Pizza Hut",
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    locality: "Sector 10",
    areaName: "Rohini",
    costForTwo: "₹350 for two",
    cuisines: ["Pizzas"],
    avgRating: 4,
    parentId: "721",
    avgRatingString: "4.0",
    totalRatingsString: "5K+",
    sla: {
      deliveryTime: 29,
      lastMileTravel: 2.3,
      serviceability: "SERVICEABLE",
      slaString: "25-30 mins",
      lastMileTravelString: "2.3 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
  {
    id: "326440",
    name: "Punjabi Angithi (Vegorama Group)",
    cloudinaryImageId: "g2pklvjnapzfoc4ackou",
    locality: "Paschim Vihar",
    areaName: "Paschim Vihar",
    costForTwo: "₹400 for two",
    cuisines: [
      "North Indian",
      "Chinese",
      "Tandoor",
      "Punjabi",
      "Thalis",
      "Snacks",
    ],
    avgRating: 4.3,
    veg: true,
    parentId: "465050",
    avgRatingString: "4.3",
    totalRatingsString: "10K+",
    sla: {
      deliveryTime: 36,
      lastMileTravel: 5,
      serviceability: "SERVICEABLE",
      slaString: "35-40 mins",
      lastMileTravelString: "5.0 km",
      iconType: "ICON_TYPE_EMPTY",
    },
  },
];
